### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by avtar** [inclusive-design/inclusivedesign.ca#5]
- [ ] https://inclusivedesign.ca/inclusive-design-embraced-by-mircosoft/
	403	https://www.fastcodesign.com/3054927/the-big-idea/microsofts-inspiring-bet-on-a-radical-new-type-of-design-thinking

- [ ] https://inclusivedesign.ca/announcing-the-launch-of-the-inclusive-design-institute/
	400	http://g.co/maps/wrfce

- [ ] https://inclusivedesign.ca/in-series-presents-jammers-an-inclusive-game-jam-workshop/
	404	http://inclusivedesign.ca/wp-content/uploads/2015/04/IN-Series-Jammers.pdf
	404	http://inclusivedesign.ca/wp-content/uploads/2015/04/Jammers-Registration-Form-Attachment-Online-JR.docx

- [ ] https://inclusivedesign.ca/ocad-university-accepting-applications-for-inclusive-design-professor/
	404	http://www.ocadu.ca/about_ocad/human_resources/employment_opportunities/faculty_instructors/tenure-track_FOD_inclusive_design.htm

- [ ] https://inclusivedesign.ca/research/mobile/
	lookup zenit.senecac.on.ca: no such host	http://zenit.senecac.on.ca/wiki/index.php/Fedora_ARM_Secondary_Architecture
	lookup zenit.senecac.on.ca: no such host	http://zenit.senecac.on.ca/wiki/index.php/NexJ_Express

- [ ] https://inclusivedesign.ca/reflections-of-a-first-time-attendee-at-the-web-for-all-conference-montreal-2016/
	404	http://www.afb.org/blog/afb-blog/reflections-of-a-first-time-attendee-at-the-web-for-all-conference/12

- [ ] https://inclusivedesign.ca/a-conversation-on-the-future-of-physician-assisted-death/
	410	http://goo.gl/forms/4Mpp3ouvYe

- [ ] https://inclusivedesign.ca/iidex-2016/
	404	http://www.iidexcanada.com/conference/summits/national-summit-on-accessibility-2016

- [ ] https://inclusivedesign.ca/idi-to-host-tetra-chapter-meeting/
	400	http://g.co/maps/mr7ar
	404	https://inclusivedesign.ca/disrupting-undoing/

- [ ] https://inclusivedesign.ca/public-forum-design-of-public-spaces-in-the-built-environment/
	403	http://www.mcss.gov.on.ca/en/mcss/programs/accessibility/regulations/reg_191/index_reg.aspx
	404	http://www.ocadu.ca/about_ocad/accessibility/servicealerts.htm
	lookup dev.inclusivedesign.ca: no such host	http://dev.inclusivedesign.ca/wp-content/uploads/2012/09/Poster-Public-Spaces-Forum-724x1024.png

- [ ] https://inclusivedesign.ca/research/
	lookup zenit.senecac.on.ca: no such host	http://zenit.senecac.on.ca/wiki/index.php/Big_Blue_Button/
	lookup zenit.senecac.on.ca: no such host	http://zenit.senecac.on.ca/wiki/index.php/Fedora_ARM_Secondary_Architecture/

- [ ] https://inclusivedesign.ca/research/york/
	400	http://g.co/maps/6cyr7

- [ ] https://inclusivedesign.ca/upcoming-talks-on-inclusive-digital-education-and-inclusive-design-2016/
	410	https://oculaspring.wordpress.com/
	error when dialing 123.255.64.15:443: dial tcp4 123.255.64.15:443: connect: connection refused	https://events.keep.edu.hk/webed/2016/
	lookup universalinclusion.unito.it: no such host	http://universalinclusion.unito.it/en/

- [ ] https://inclusivedesign.ca/research/implementation/
	lookup zenit.senecac.on.ca: no such host	http://zenit.senecac.on.ca/wiki/index.php/Big_Blue_Button

- [ ] https://inclusivedesign.ca/idrc-partners-with-lumen-learning-to-create-next-generation-courseware/
	404	https://inclusivedesign.ca/waking-the-machines-assistive-technologies-and-prosthetic-agency/
	404	http://lumenlearning.com/ann-courseware-challenge/
	404	http://www.gatesfoundation.org/Media-Center/Press-Releases

- [ ] https://inclusivedesign.ca/aegis-open-accessibility-framework/
	lookup dev.inclusivedesign.ca: no such host	http://dev.inclusivedesign.ca/wp-includes/js/tinymce/plugins/wordpress/img/trans.gif

- [ ] https://inclusivedesign.ca/abilities-arts-festival-at-ocad-universitys-open-gallery/
	error when dialing 31.170.123.89:80: dial tcp4 31.170.123.89:80: i/o timeout	http://abilitiesartsfestival.org/
	error when dialing 31.170.123.89:80: dialing to the given TCP address timed out	http://abilitiesartsfestival.org/events/current-festival/scotiabank-nuit-blanche/

- [ ] https://inclusivedesign.ca/people/
	400	http://www.ehealthinnovation.org/
	403	http://www.ucd.ie/
	404	http://blogs.oii.ox.ac.uk/cobo
	404	http://books.google.ca/books?id=4AcGvt3oX6IC
	404	http://www.ocadu.ca/research/imagination-catalyst/ic-incubator.htm
	404	http://www.oise.utoronto.ca/sese/
	404	http://www.ryerson.ca/ds/
	404	http://www.senecac.on.ca/ori/
	404	http://www.torontomu.ca/itm/
	406	http://www.knowledgeforum.com/
	error when dialing 128.100.71.3:80: dialing to the given TCP address timed out	http://ibbme.utoronto.ca/
	error when dialing 128.86.130.42:80: dialing to the given TCP address timed out	http://www.lon.ac.uk/
	error when dialing 142.150.97.187:80: dialing to the given TCP address timed out	http://encorelab.org
	error when dialing 192.195.43.123:80: dialing to the given TCP address timed out	http://www.socsci.ulster.ac.uk/
	error when dialing 192.195.43.223:80: dialing to the given TCP address timed out	http://www.ulster.ac.uk/
	error when dialing 199.250.194.80:80: dialing to the given TCP address timed out	http://www.creativeclass.com/
	error when dialing 199.250.194.80:80: dialing to the given TCP address timed out	http://www.creativeclass.com/_v3/whos_your_city/
	lookup research.ocadu.ca: no such host	http://research.ocadu.ca/mobilelab/home
	lookup www.gdial.ca: no such host	http://www.gdial.ca
	lookup www.signlinkstudio.ca: no such host	http://www.signlinkstudio.ca

- [ ] https://inclusivedesign.ca/workshop-the-business-advantages-of-making-special-the-norm/
	404	http://www.viscardicenter.org/news-events/events/nbdc-distance-learning.html
	404	http://www.viscardicenter.org/services/nbdc/

**Comment by avtar** [comment]
Steps used to crawl the site and generate a list of broken links:

1. Install the following two Homebrew packages: ``brew install muffet peterldowns/tap/localias``
2. Clone this repository and serve it using a local web server: ``python3 -m http.server 9000``
3. Configure a usable test domain:
   ```
   localias set http://inclusivedesign.test 9000
   localias run
   ```
4. Generate list of broken links:
   ```
   muffet \
   --ignore-fragments \
   --skip-tls-verification \
   --exclude '^http://inclusivedesign.test/wp-.*$' \
   --exclude '^http://inclusivedesign.test/xmlrpc.*$' \
   --exclude '^https://www.ontario.ca' \
   http://inclusivedesign.test
   ```

**Comment by chosww** [comment]
@avtar, I am getting a warning when I run brew install muffet localias: 
`No available formula with the name "localias".`

**Comment by avtar** [comment]
@chosww I updated my notes above. Try this command instead: ``brew install muffet peterldowns/tap/localias``
